### ISSUE TITLE
Docker build docs is outdated

### ISSUE THREAD

**Issue by iammarkps** [supabase/postgres#240]
# Improve documentation

## Link 

https://github.com/supabase/postgres/wiki/Docker

## Describe the problem

I think that ansible is not working anymore, it should suggest building with docker instead of using ansible to build the docker images.

## Describe the improvement

Use docker build instead

**Comment by jimkoen** [comment]
I second this. Giving a little bit more info on how to use the playbooks would be much appreciated.
For example, my current attempt at building the container fails at the `[postgis - build SFCGAL]` task:

![Bildschirmfoto 2022-10-05 um 05 05 10](https://user-images.githubusercontent.com/46608440/193972262-a7aefe99-ecbb-4d6c-9c87-75ab80862c03.png)

Forgive me for posting screenshots, but the actual error message is several thousand lines long, as the entire Build + gmake Progress got inserted into the task output.

If you can't allocate resources rn to maintain the playbooks, just giving a little bit of guidance would be great. I have a bit of experience with ansible and would be willing to put time into this to get this working.

**Comment by jimkoen** [comment]
To clarify what the previous poster meant by "use docker build instead":

Any ordinary person would assume that [following the wiki entry](https://github.com/supabase/postgres/wiki/Docker), you'd want to run the playbooks in the `/ansible/` directory on your local machine, or on some linux machine and it'll somehow prepare the build environment and trigger a docker build for obtaining a usable docker image. When this doesn't work, you'd conclude that something mutch more far fetched is meant: to run the playbook against a fresh ubuntu or postgres docker container, i.e. having the container as a host inside the inventory and executing the playbook from localhost or something of that sort.

**However BOTH approaches are wrong and lead to errors!**

What is meant by "Use docker build instead": The wiki is outdated and references an earlier stage in the project where the docker images where actually built in one of the ways mentioned above.

This has however now been deprecated and the playbooks are supposed to run from within a fresh postgres docker container, which is triggered by **"using the  Dockerfile in the project root to use `docker build` to build a container image instead of running the ansible playbooks".**

So the build the container image, in project root run:

`docker build --tag yourname/supabase_postgres_custom:latest --build-arg VERSION=14.1 .`

Substitue `VERSION` with the correct postgres docker image tag.

Because the playbooks are supposed to run as part of the docker build from within the fresh postgres container, to provision it for supabase. Which is indicated in the dockerfile, since ansible is copied into the container and the JDK is installed. Both points where the source of errors that people mentioned a lot previously.

FFS update the wiki

**Comment by darora** [comment]
Hey folks - thanks for pointing out that this was outdated. I've updated the wiki, and will likely migrate the content from there to be contained within the repository soon.
