### ISSUE TITLE
 ERROR:  relation "pgsodium.key" does not exist

### ISSUE THREAD

**Issue by BarnabyShearer** [supabase/postgres#274]
With the Docker image `14.1.0.34` and before `CREATE EXTENSION IF NOT EXISTS pgsodium WITH SCHEMA extensions;` worked as expected.

Using `14.1.0.55` it gives `line 8: /etc/postgresql-custom/pgsodium_root.key: No such file or directory invalid secret key`

Using `14.1.0.61` it gives `ERROR:  relation "pgsodium.key" does not exist`

**Comment by michelp** [comment]
There was a bug in the latest pgsodium release where there was a missing `@extschema@` in one place and was accidentally hardwired to `pgsodium` so that has caused this error because you are trying to install pgsodium into a schema not named `pgsodium`.

Due to pgsodium's special nature as a security sensitive component, and because other heterogeneous components must refer to it and know where its objects are a priori, we have decided to "peg" pgsodium's schema to `pgsodium` by setting `schema = pgsodium` in it's Extension control file and making it non-relocatable.  This is what the extension packaging documentation recommends so we're going to have create some minor breakage (such as you see) with anyone who has installed it into extensions.  

I apologize for any errors this may cause, but it's for the best given the nature of the secret handling functionality in pgsodium.  The current release also creates 102 objects, which increases the probability of name collision in the `extensions` schema in the future anyway.  

The easiest workaround for you is to `CREATE SCHEMA pgsodium; CREATE EXTENSION pgsodium WITH SCHEMA pgsodium` and update any references you have to be prefixed with `pgsodium.`.  This is the best and most secure and future proof way to go.   Alternatively you can put the `pgsodium` schema in your `search_path` so that it comes before extensions.

**Comment by BarnabyShearer** [comment]
Thank you, moving it to the `pgsodium` schema did indeed work.
