### ISSUE TITLE
SSL enabled by default

### ISSUE THREAD

**Issue by acrogenesis** [supabase/postgres#37]
# Feature request

## Is your feature request related to a problem? Please describe.
I'm deploying to a test server on digitalocean and noticed SSL isn't enabled by default.

## Describe the solution you'd like
Perhaps there could be a "setup-wizard" to enable SSL or if it can be done since the beginning better

**Comment by acrogenesis** [comment]
If you set `ssl = on` on `/etc/postgresql/12/main/postgresql.conf` it works. Are the keys created on deploy or are they the same for every image?

**Comment by inian** [comment]
Hey @acrogenesis, you will need to specify your own certs and keys for this which is why we don't enable it by default. The default key is snakeoil.pem which is the same for every image. So the recommended way is to have a startup script modify `postgresql.conf` to enable ssl and generate keys and certs.
