### ISSUE TITLE
Change default logging level 

### ISSUE THREAD

**Issue by inian** [supabase/postgres#43]
It will be useful to have more detailed logging 

Explore the following parameters
- log_statement
- log_min_messages
- log_connections

**Comment by awalias** [comment]
for project pausing I think `log_connections` would be enough for me if it works as expected

also we probably want to enable log rotation from `postgresql.conf`

**Comment by inian** [comment]
In general for debugging issues and exposing them in the dashboard, it will be useful to have a higher logging level. Was debugging one or two issues with @steve-chavez where we were wishing for greater visibility into what was happening.

**Comment by steve-chavez** [comment]
Yes, I remember we wanted to see the prepared statement parameters of some SELECT queries(`SELECT.. WHERE id = $param`) that failed with weird errors(somehow the parameters where not being passed fully). We managed to debug this with Kong logs though - they showed the parameters on the request query string.

For that we would require a `log_statement=all`. Not sure if it's totally worth it because logs get huge fast.

**Comment by pashkinelfe** [comment]
log_statement=all to me seems an overkill and will generate very big and detailed logs. But it may be useful to log DDL operations only as they are not often i.e. log_statement=ddl

**Comment by pashkinelfe** [comment]
Seems as though it's not hard to implement this the discussion stalled for 2 years. So let's leave logging level unchanged until it's needed for something actual.
