### ISSUE TITLE
How to native install

### ISSUE THREAD

**Issue by dmbr0** [supabase/postgres#985]
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

That I need to use docker 
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. I should be able to create and initialize postgres to be compatible with supabase wherever I host postgres without having to dig and dig and dig. The documentation should be clear. 
2. shouldn't need docker. I don't use AWS. I don't use Digital Ocean. There is no clear way to setup my postgres database to be compatible with self hosted without docker. 

Should be able to run a script and have my postgres database setup and initialized regardless of host.

**Comment by olirice** [comment]
Packaging postgres with 12+ extensions is not something that you can do reliably without having knowledge of the build hardware, OS etc.

We use the AWS AMIs for the hosted platform and docker for local hosting via the supabase CLI

We're transitioning to use nix as our build tool which will also enable native builds on linux machines with a goal of adding support for MacOS in coming weeks. We don't currently plan to target windows

You can track that work here https://github.com/supabase/postgres/pull/1012 if you're interested

**Comment by olirice** [comment]
the beginnings of local install are in place

first install nix https://github.com/supabase/postgres/blob/develop/nix/docs/start-here.md

then you can start the server with
```
nix run .#start-client 15
```
to get the bare bones postgres build

If you want all the SQL setup that is present on the cloud hosted offering then you can run
```
nix run .#start-client-and-migrate 15
```
which applies those migrations and drops you into a psql shell

This is intended to be a development flow for the repository, not a method for self hosting

We will make progress along the goals you outlined but I'm going to close this issue as out-of-scope because, while we might complete some of them incidentally, they are non-goals for the project

**Comment by dmbr0** [comment]
I have postgres running on Freebsd. All I want is to install the required extensions and run the required migrations to make it usable by self hosted and not use postgres with docker.

I keep reading "make it easy to get started with postgres" and "we're committed to self hosting and open source"

I know my hardware and OS. I can take care of that. Finding what's required to make my postgres database work with the rest of supabase seems to be buried somewhere. 

It's unfortunate because instead of actually using supabase, finding bugs, and giving feedback, I'm spending time digging around trying to figure out how to make it work.

**Comment by olirice** [comment]
> All I want is to install the required extensions and run the required migrations to make it usable by self hosted and not use postgres with docker

unfortunately this is more difficult than it sounds. Supabase supports > 30 extensions, all with their own dependencies and build idiosyncrasies. You can install postgres natively using the nix steps I outlined above to avoid docker overhead, but again, that is intended as a method for local development rather than a self-hosting method

at this point the we don't support native installs on FreeBSD for self hosting users
